version: '3.8'

services:
  api:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: api
    networks:
      - app_network
    environment:
      - DATABASE_URL=${DATABASE_URL}
    ports:
      - "8000:8000"

  db:
    image: postgres:15-alpine
    container_name: db
    networks:
      - app_network
    environment:
      - POSTGRES_USER=${DB_USER}
      - POSTGRES_PASSWORD=${DB_PASSWORD}
      - POSTGRES_DB=${DB_NAME}
    volumes:
      - postgres_data:/var/lib/postgresql/data

networks:
  app_network:
    driver: bridge

volumes:
  postgres_data:
